// <auto-generated />
using System;
using BESMIK.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BESMIK.DAL.Migrations
{
    [DbContext(typeof(BesmikDbContext))]
    [Migration("20240815102039_personelrole1")]
    partial class personelrole1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BESMIK.Entities.Concrete.Advance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AdvanceRequestDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("AdvanceResponseDate")
                        .HasColumnType("date");

                    b.Property<int>("AdvanceType")
                        .HasColumnType("int");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Advances");
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<float?>("Wage")
                        .HasColumnType("real");

                    b.Property<DateOnly?>("WorkEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WorkStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "Ankara, Türkiye",
                            BirthDate = new DateOnly(2000, 1, 1),
                            BirthPlace = "Yozgat",
                            ConcurrencyStamp = "3d6f58f6-219a-407b-9cbd-71d5f3285ede",
                            Department = 1,
                            Email = "site.yoneticisi@bilgeadam.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            Job = "İK",
                            LockoutEnabled = false,
                            Name = "Site",
                            NormalizedEmail = "SITE.YONETICISI@BILGEADAM.COM",
                            NormalizedUserName = "SITEYONETICISI",
                            PasswordHash = "AQAAAAIAAYagAAAAEJowJ4bs10Z3tx+jDke/fVOgMj2tC2s1rZIOZ9qh2BDj/RbOnf7aAawzsamuqFVrIg==",
                            Phone = "+90 123 456 7890",
                            PhoneNumberConfirmed = false,
                            SecondName = "Yöneticisi",
                            SecurityStamp = "d9737378-9ebb-4c92-8c40-eddfb3abe6d6",
                            Surname = "Yönetici",
                            Tc = "12345678901",
                            TwoFactorEnabled = false,
                            UserName = "siteyoneticisi",
                            WorkStartDate = new DateOnly(1996, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "Ankara, Türkiye",
                            BirthDate = new DateOnly(1980, 1, 1),
                            BirthPlace = "Ankara",
                            CompanyId = 2,
                            ConcurrencyStamp = "25e0f12e-f7f7-43da-bb52-4c4858f523c6",
                            Department = 9,
                            Email = "personel1.personel@bilgeadam.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            Job = "Bilgisayar Mühendisi",
                            LockoutEnabled = false,
                            Name = "Fadime",
                            NormalizedEmail = "PERSONEL1.PERSONEL@BILGEADAM.COM",
                            NormalizedUserName = "PERSONEL1",
                            PasswordHash = "AQAAAAIAAYagAAAAENIsQJMvMW4Zq+3Rb/tFt389U9FoZ4/GTM6oQBqlsZBN6wO4BbX2DCiZMfqorA8yaw==",
                            Phone = "+90 123 456 7890",
                            PhoneNumberConfirmed = false,
                            Photo = "AcKedi.jpg",
                            SecurityStamp = "7aa2e035-5bb2-4263-8a28-4a190d599025",
                            Surname = "Güngörmemiş",
                            Tc = "14725836914",
                            TwoFactorEnabled = false,
                            UserName = "personel1",
                            Wage = 150000f,
                            WorkStartDate = new DateOnly(2000, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "Ankara, Türkiye",
                            BirthDate = new DateOnly(1980, 1, 1),
                            BirthPlace = "Ankara",
                            CompanyId = 2,
                            ConcurrencyStamp = "b1820591-8fa4-4f5c-82e7-9c624926eb36",
                            Department = 3,
                            Email = "personel2.personel@bilgeadam.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            Job = "İnşaat Mühendisi",
                            LockoutEnabled = false,
                            Name = "Kezban",
                            NormalizedEmail = "PERSONEL2.PERSONEL@BILGEADAM.COM",
                            NormalizedUserName = "PERSONEL2",
                            PasswordHash = "AQAAAAIAAYagAAAAELvydV+YMib16j4BW846N3YpglK+SCE8oqaaNn0Vm0wlSlybHUUbo8YIy66T48pbdg==",
                            Phone = "+90 123 456 1111",
                            PhoneNumberConfirmed = false,
                            Photo = "AcKedi.jpg",
                            SecurityStamp = "8634969f-40b5-4e55-a52a-6c38c2fdf105",
                            Surname = "Günyüzü",
                            Tc = "14725836985",
                            TwoFactorEnabled = false,
                            UserName = "personel2",
                            Wage = 250000f,
                            WorkStartDate = new DateOnly(2000, 1, 1)
                        });
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ContractEndYear")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ContractStartYear")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeesNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EstablishmentYear")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MersisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PictureFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TaxAdministration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ankara, Türkiye",
                            ContractEndYear = new DateOnly(2025, 1, 1),
                            ContractStartYear = new DateOnly(2020, 1, 1),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@teknolojiyenilikcileri.com",
                            EmployeesNumber = "50",
                            EstablishmentYear = new DateOnly(2010, 5, 1),
                            IsActive = true,
                            MersisNumber = "1234567890123456",
                            Name = "Teknoloji Yenilikçileri",
                            Phone = "+90 312 555 1234",
                            TaxAdministration = "Ankara",
                            TaxNumber = "1234567890",
                            TitleName = "A.Ş."
                        },
                        new
                        {
                            Id = 2,
                            Address = "İstanbul, Türkiye",
                            ContractEndYear = new DateOnly(2024, 3, 1),
                            ContractStartYear = new DateOnly(2019, 3, 1),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@rollinemuhendislik.com",
                            EmployeesNumber = "200",
                            EstablishmentYear = new DateOnly(2005, 8, 15),
                            IsActive = true,
                            MersisNumber = "9876543210987654",
                            Name = "Rolline Mühendislik",
                            Phone = "+90 212 444 5678",
                            TaxAdministration = "İstanbul",
                            TaxNumber = "0987654321",
                            TitleName = " Ltd."
                        });
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.CompanyManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PictureFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("WorkStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyManagers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ankara, Türkiye",
                            BirthDate = new DateOnly(1985, 7, 15),
                            BirthPlace = "Ankara",
                            CompanyId = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 9,
                            Email = "ahmet.yilmaz@teknolojiyenilikcileri.com",
                            Name = "Ahmet",
                            Phone = "+90 532 111 2233",
                            Profession = "Mühendis",
                            SecondName = "Murat",
                            SecondSurname = "Kaya",
                            Surname = "Yılmaz",
                            TC = "12345678901",
                            WorkStartDate = new DateOnly(2010, 9, 1)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Tunceli, Türkiye",
                            BirthDate = new DateOnly(1990, 4, 20),
                            BirthPlace = "İstanbul",
                            CompanyId = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 6,
                            Email = "elif.demir@rollinemuhendislik.com",
                            Name = "Elif",
                            Phone = "+90 212 333 4455",
                            Profession = "Dış Ticaret Sorumlusu",
                            SecondName = "Nur",
                            SecondSurname = "Yıldız",
                            Surname = "Demir",
                            TC = "98765432109",
                            WorkStartDate = new DateOnly(2015, 6, 15)
                        });
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("OffDaysNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PermissionEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PermissionRequestDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PermissionResponseDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PermissionStartDate")
                        .HasColumnType("date");

                    b.Property<int>("PermissionStatus")
                        .HasColumnType("int");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.Spending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpendingCurrency")
                        .HasColumnType("int");

                    b.Property<string>("SpendingFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SpendingRequestDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SpendingResponseDate")
                        .HasColumnType("date");

                    b.Property<int>("SpendingStatus")
                        .HasColumnType("int");

                    b.Property<int>("SpendingType")
                        .HasColumnType("int");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Spendings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Site Yöneticisi",
                            NormalizedName = "SITE YONETICISI"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Şirket Yöneticisi",
                            NormalizedName = "SIRKET YONETICISI"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Personel",
                            NormalizedName = "PERSONEL"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.Advance", b =>
                {
                    b.HasOne("BESMIK.Entities.Concrete.AppUser", "AppUser")
                        .WithMany("Advances")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.AppUser", b =>
                {
                    b.HasOne("BESMIK.Entities.Concrete.Company", "Company")
                        .WithMany("AppUsers")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.CompanyManager", b =>
                {
                    b.HasOne("BESMIK.Entities.Concrete.Company", "Company")
                        .WithMany("CompanyManagers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.Permission", b =>
                {
                    b.HasOne("BESMIK.Entities.Concrete.AppUser", "AppUser")
                        .WithMany("Permissions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.Spending", b =>
                {
                    b.HasOne("BESMIK.Entities.Concrete.AppUser", "AppUser")
                        .WithMany("Spendings")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BESMIK.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BESMIK.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BESMIK.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BESMIK.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.AppUser", b =>
                {
                    b.Navigation("Advances");

                    b.Navigation("Permissions");

                    b.Navigation("Spendings");
                });

            modelBuilder.Entity("BESMIK.Entities.Concrete.Company", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("CompanyManagers");
                });
#pragma warning restore 612, 618
        }
    }
}
